### ISSUE TITLE
Partial page transition

### ISSUE THREAD

**Issue by Ruffio** [dgileadi/zepto-page-transitions#11]
Hi.

I have tried this plugin and it works very well :-) Thanks for a nice job.

As I'm going to be using multipage templates I would like to be able to only transition a part of the page leaving header and footer intact. 

I have packed all my pages inside a div and it would be wounderful if the 'pages' only where living inside this div and not the complete page. The reason is to save alot of header and footers. I don't know if it makes any sense. I have tried changing some of the css but unfortunately not the right way :-(

I have made a sample here: http://mbrevis.com/admin/

Kindly regards Ruffio

**Comment by dgileadi** [comment]
Thanks for the suggestion, and for the kind words!.  I'll take a look at it and see if it's something I want to add.

**Comment by dgileadi** [comment]
I changed the script to add the "ui-page" class to page divs instead of setting style attributes on the divs directly.  I also added the new div.ui-page rule to transition.css.  I don't know if this will help you, but maybe it'll allow you to accomplish what you want.

**Comment by Ruffio** [comment]
Hi I have pulled the latest code and tried without any luck :-( I can see, that you set pages.attr('style', 'position: absolute; width: 100%; height: 100%; left: 0px; top: 0px;'); 

Doesn't that 'overwrite' my existing css? I mean, the above tells the browser, that the page div fills the whole viewport, right?

**Comment by dgileadi** [comment]
The latest code uses pages.addClass('ui-page'); instead of pages.attr('style' ...).  That was the change I made.  My thinking was that you might be able to modify the div.ui-page rule inside transition.css to match what you want.

**Comment by Ruffio** [comment]
I have tried to change the css but still with no luck. I have actually reorganised my pages so it's full page transition thereby using the 'native' usage but without luck. It is like that after the (fade)transition has completed the original css (my other css) is cleared :-(

I have updated my test website so you can see for yourself.

**Comment by Ruffio** [comment]
No problems. Error was related to error # 16: https://github.com/dgileadi/zepto-page-transitions/issues/16
