### ISSUE TITLE
Setting default values using javascript

### ISSUE THREAD

**Issue by Ruffio** [dgileadi/zepto-page-transitions#15]
I'm trying to set the default transition to slide by using this javascript per instruction:

<script type="text/javascript">$(document.body).transition('options', { defaultPageTransition: 'slide', domCache: false});</script>

But the default transition is not slide :-(

What do I do wrong?

**Comment by dgileadi** [comment]
This works for me.  I used something like:

```
<script type="text/javascript">
    $(function($){
        $(document.body).transition('options', {defaultPageTransition: 'slide'});
    });
</script>
```

Also be aware that the default transition will be overridden by any transition attribute specified on links; it only applies to links without a transition attribute.
