### ISSUE TITLE
'FromPage' jumps to the top upon page transition when using history.back() if you have scrolled down

### ISSUE THREAD

**Issue by Ruffio** [dgileadi/zepto-page-transitions#22]
If you have scrolled down on a page and then use history.back(); to transition back to previous page then the 'fromPage' jumps to the top before transition is performed.

'Live' test:
1. Go to: http://mbrevis.com/admin/
2. Select 'Layout'
3. Select 'Sidefod'
4. Scroll down to bottom
5. Press 'Tilbage' in top of page (to execute history.back();)
6. The page jumps to the top and then the transition is performed

Kindly regards

**Comment by dgileadi** [comment]
Apparently the browser is causing the jump itself.  I can't think of a good way to fix it.  Let me know if you have any idea; closing for now.
