### ISSUE TITLE
The browser forward button uses the default transition

### ISSUE THREAD

**Issue by dgileadi** [dgileadi/zepto-page-transitions#23]
1. Go to: http://mbrevis.com/admin/
2. Select 'Layout'
3. Click the back button
4. Click the forward button

Results: the forward button's transition moves in the wrong direction.

**Comment by dgileadi** [comment]
This is because we don't currently store history state for moving forward.

**Comment by Ruffio** [comment]
I'm not sure that this bug is fixed. I still get wrong direction :-(

**Comment by dgileadi** [comment]
Whoops, sure enough.  Pushed the full fix.

**Comment by Ruffio** [comment]
Works like a charm :-)
