### ISSUE TITLE
The back button does an ajax load when navigating back to the start page

### ISSUE THREAD

**Issue by dgileadi** [dgileadi/zepto-page-transitions#24]
This happens because the hash (and hence the `to` variable) is empty, and the code handles an empty location by ajax-loading it.  Instead it ought to look for the default page and show it instead.

**Comment by Ruffio** [comment]
It works perfectly :-) This bug has been driving me nuts as I thought it was my code that was crazy :-)

**Comment by dgileadi** [comment]
Very glad it works for you!
