### ISSUE TITLE
examples don't work.

### ISSUE THREAD

**Issue by ghost** [dgileadi/zepto-page-transitions#3]
Hi,

Im getting this error on your examples page...

Uncaught TypeError: Property '$' of object [object Window] is not a function

**Comment by dgileadi** [comment]
Thanks for reporting this, but I wasn't able to reproduce the error.  Could you give me some more details?  What browser are you using?  How are you opening the example pages?  Which page did you open that gave you the error?

**Comment by ghost** [comment]
Hi, your response prompted me to test this at work and it works fine.  Sorry to alert a false positive, I will check my laptop configuration tonight.  Thanks for getting back to me.
