### ISSUE TITLE
Animations are not working in IE10

### ISSUE THREAD

**Issue by Fresheyeball** [dgileadi/zepto-page-transitions#39]
The attached example code does not work in IE10. Animations do not occur.

**Comment by dgileadi** [comment]
Unfortunately this is not something I plan to work on or fix, sorry; I dev on a Mac and have limited time nowadays. If you manage to find a fix feel free to submit a pull request!

**Comment by Fresheyeball** [comment]
Fair enough. I just might do that.

**Comment by Fresheyeball** [comment]
Can you point me at the section of code pertaining to the animation? Its not clear to me where and how styles get applied.

**Comment by dgileadi** [comment]
I suspect what you'll need to do is edit the animation definitions in transition.css to work with what IE10 supports.

If you need to edit the JS the "magic" all happens in the perform function, starting on line 340. There are two timeouts. The first triggers immediately and runs the transitions; the second triggers afterwards and cleans up after the transitions. So the real work for running the transitions is in the first timeout, and basically all it does is apply CSS classes to the divs. Then the CSS animation engine uses the transition classes defined in transition.css to do the actual transitioning.

**Comment by Fresheyeball** [comment]
https://github.com/dgileadi/zepto-page-transitions/blob/master/src/transition.js#L348 ok cool, I strongly suspect its not the css, but that IE10 has a nuance with the manner classes get applied. If you reopen this issue, I will reference it in the pull request.

**Comment by dgileadi** [comment]
Many thanks!
