### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by tamaska** [dgileadi/zepto-page-transitions#45]
Dear Zepto, 
probably i am missing something obvious but no way the code  seems to work...
If you could take a look at it :
 http://www.fenekpusztacastrum.com/index.html
Thank you: TPeter

<ul class="dropdown-menu ">
              <li><a transition="flip" href="kornyezet.html" >Környezettörténet</a></li>
              <li><a href="tortenet.html" >Fenékpuszta története</a></li>
              <li><a href="kutatas.html" >Kutatástörténet</a></li>
              <li><a href="asatasok.html" >Ásatások </a></li>

**Comment by dgileadi** [comment]
I’m sorry, I’m unable to help with individual installations of this code. One option for you may be to get the examples running in your local environment, and then build functionality on top of them.
