### ISSUE TITLE
Trigger events

### ISSUE THREAD

**Issue by abolinhas** [dgileadi/zepto-page-transitions#5]
Hi,

Can you explain how to use the events (eg. pageint)?

I tried use this but don't worked.
$("#demos").on('pageinit',function(){
  alert("Test");
});

Best regards

**Comment by dgileadi** [comment]
Created an example for events.  In your case if you want 'pageinit' to trigger for the initial page then put the above code before the script include for transition.min.js.

**Comment by abolinhas** [comment]
Thanks,

I have several pages into one HTML file, it is possible trigger a event per page role ?

$("#page1").on('pageshow',function(){
alert("Test");
});

$("#page2").on('pageshow',function(){
alert("Test");
});

....

Best regards
