### ISSUE TITLE
Direct link's

### ISSUE THREAD

**Issue by abolinhas** [dgileadi/zepto-page-transitions#6]
Hi,

I have several pages into one HTML file:
index.html :

<pre>
&lt;div data-role="page" id="home"&gt;
&lt;/div&gt;
&lt;div data-role="page" id="demos"&gt;
&lt;/div&gt;
&lt;a href="#home"&gt;Go to home&lt;/a&gt;
&lt;a href="#demos"&gt;Go to demos&lt;/a&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>

When I access to my page through www.domain.com/teste/index.html or www.domain.com/teste/index.html#home I have no problems but if i try through www.domain.com/teste/index.html#demos I get several problems.

It is not possible access to a page through direct link ?

Best regards

**Comment by dgileadi** [comment]
Turns out support for this wasn't too hard, added it.

**Comment by abolinhas** [comment]
Many thanks,

Work like a charm :)
