### ISSUE TITLE
Using this in wordpress

### ISSUE THREAD

**Issue by sincero** [dgileadi/zepto-page-transitions#8]
Hello, I love the idea of this, but im having problems getting this to work with a wordpress blog. I added the transitions tags to my links, and I included the files in the exact order as you did, but no luck. I thought it might be because wp calls .php files instead of your html file in the example, but im not sure. Also, I have <li> tags wrapped around my anchor tags, is that a problem?

**Comment by dgileadi** [comment]
I'm sorry you're having trouble.  Unfortunately as an unpaid developer working on this project in my spare time I'm unable to help you to get it working on your site.  I can say that .php files shouldn't make a difference, and neither should the li tags.  Perhaps you can find a javascript developer who can help you out.
